$ErrorActionPreference = 'Stop'
$path = 'src/pages/Configuracion.tsx'
$text = Get-Content $path -Raw

$replacements = [System.Collections.Generic.Dictionary[string,string]]::new([System.StringComparer]::Ordinal)

function Add-Map([string]$k, [string]$v) {
  if (-not $replacements.ContainsKey($k)) {
    $replacements.Add($k, $v)
  }
}

# Mojibake con +�
Add-Map 'definici+�n' 'definición'
Add-Map 'par+�metro' 'parámetro'
Add-Map 'par+�metros' 'parámetros'
Add-Map 'Producci+�n' 'Producción'
Add-Map 'An+�lisis' 'Análisis'
Add-Map 'N+�mero' 'Número'
Add-Map 'S+�/No' 'Sí/No'
Add-Map 'Relaci+�n' 'Relación'
Add-Map 'jer+�rquico' 'jerárquico'
Add-Map '+�rea' 'área'
Add-Map 'edici+�n' 'edición'
Add-Map 'eliminaci+�n' 'eliminación'
Add-Map 'vac+�a' 'vacía'

# Reemplazos con ?
Add-Map 'Configuraci?n' 'Configuración'
Add-Map 'definici?n' 'definición'
Add-Map 'M?dulo' 'Módulo'
Add-Map 'M?dulos' 'Módulos'
Add-Map 'm?dulo' 'módulo'
Add-Map 'm?dulos' 'módulos'
Add-Map 'b?squeda' 'búsqueda'
Add-Map 'B?squeda' 'Búsqueda'
Add-Map 'par?metro' 'parámetro'
Add-Map 'par?metros' 'parámetros'
Add-Map 'versi?n' 'versión'
Add-Map 'descripci?n' 'descripción'
Add-Map 'Descripci?n' 'Descripción'
Add-Map 'C?digo' 'Código'
Add-Map 'C?lculo' 'Cálculo'
Add-Map 'N?mero' 'Número'
Add-Map 'S?/No' 'Sí/No'
Add-Map 'Relaci?n' 'Relación'
Add-Map 'producci?n' 'producción'
Add-Map 'm?nimo' 'mínimo'
Add-Map 'M?nimo' 'Mínimo'
Add-Map 'm?x' 'máx'
Add-Map 'm?ltiples' 'múltiples'
Add-Map 'vac?o' 'vacío'
Add-Map 'acci?n' 'acción'
Add-Map 'operaci?n' 'operación'
Add-Map 'eliminaci?n' 'eliminación'
Add-Map 'regresi?n' 'regresión'
Add-Map 'reversi?n' 'reversión'
Add-Map 'Activar?s' 'Activarás'
Add-Map 'qu?' 'qué'
Add-Map 'Qu?' 'Qué'
Add-Map 'est?' 'está'
Add-Map 'est?n' 'están'
Add-Map 's?lo' 'sólo'
Add-Map 'S?' 'Sí'
Add-Map 'm?s' 'más'
Add-Map 'a?n' 'aún'
Add-Map 'tambi?n' 'también'
Add-Map 'p?gina' 'página'
Add-Map 'auditor?a' 'auditoría'
Add-Map 'gu?a' 'guía'
Add-Map 'opci?n' 'opción'
Add-Map 'selecci?n' 'selección'
Add-Map 'aplicar?n' 'aplicarán'
Add-Map 'crear?n' 'crearán'
Add-Map 'estar?amos' 'estaríamos'
Add-Map 'podr?' 'podrá'
Add-Map 'Podr?s' 'Podrás'
Add-Map 'quedar?' 'quedará'
Add-Map 'quedar?n' 'quedarán'
Add-Map 'autom?ticamente' 'automáticamente'
Add-Map 'espec?fico' 'específico'
Add-Map 'espec?ficos' 'específicos'
Add-Map 'simult?neamente' 'simultáneamente'
Add-Map 'r?pido' 'rápido'
Add-Map 'r?pida' 'rápida'
Add-Map 'r?pidas' 'rápidas'
Add-Map 'reci?n' 'recién'
Add-Map 'b?sica' 'básica'
Add-Map 'B?sico' 'Básico'
Add-Map 'b?sicos' 'básicos'
Add-Map 'Cat?logo' 'Catálogo'
Add-Map 'Hect?reas' 'Hectáreas'
Add-Map 'Pa?s' 'País'
Add-Map 'P?rez' 'Pérez'
Add-Map 'Contrase?a' 'Contraseña'
Add-Map 'T?' 'Tú'
Add-Map 't?cnico' 'técnico'
Add-Map 'v?lido' 'válido'
Add-Map '?ltima' 'última'
Add-Map '?ltimo' 'último'
Add-Map '?lt.' 'últ.'
Add-Map '?nica' 'única'
Add-Map '?rea' 'área'
Add-Map 'Est?ndar' 'Estándar'
Add-Map 'Gesti?n' 'Gestión'
Add-Map 'informaci?n' 'información'
Add-Map 'jerarqu?a' 'jerarquía'
Add-Map 'Validaci?n' 'Validación'
Add-Map 'Distribuci?n' 'Distribución'
Add-Map 'Direcci?n' 'Dirección'
Add-Map 'Personalizaci?n' 'Personalización'
Add-Map 'Asignaci?n' 'Asignación'
Add-Map 'Justificaci?n' 'Justificación'
Add-Map 'Protecci?n' 'Protección'
Add-Map 'Agrupaci?n' 'Agrupación'
Add-Map 'Activaci?n' 'Activación'
Add-Map 'Secci?n' 'Sección'
Add-Map 'sesi?n' 'sesión'
Add-Map 'restricci?n' 'restricción'
Add-Map 'expl?cito' 'explícito'
Add-Map 'plantaci?n' 'plantación'
Add-Map 'Macrot?nel' 'Macrotúnel'
Add-Map 'pesta?a' 'pestaña'

# Símbolos y frases puntuales
Add-Map '�Ǫ' '…'
Add-Map '?C' '°C'
Add-Map '? Seleccionar definición ?' '— Seleccionar definición —'
Add-Map '? Seleccionar campo ?' '— Seleccionar campo —'
Add-Map '? Mismo que mostrar ?' '— Mismo que mostrar —'
Add-Map '?? Global ? todos los cultivos' 'Global - todos los cultivos'
Add-Map '?? {c.nombre}' '{c.nombre}'
Add-Map '<span>?</span>' '<span>·</span>'
Add-Map '-+Eliminar ' '¿Eliminar '

foreach ($k in $replacements.Keys) {
  $text = $text.Replace($k, $replacements[$k])
}

$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($path, $text, $enc)
Write-Output 'OK'
